#!/bin/bash

# Create HTML and DocX builds from Markdown Master files
# in terminal enter: ./panexec

##--------- list powerpoints on index, Make sure to upload first! ------------------##

# make a markdown list of all pptx files as downloadable links

cd slideshows

for i in *.pptx; do echo "  * ["$i"](http://jonathangabel.com/documents/art125/ppt/"$i")" >> showlist.md; done

perl -pi -w -e 's/\[Art125Unit0?(\d+)-0?(\d+)\.(\w*)\.pptx/\[Unit $1-$2: $3/g;' showlist.md

mv showlist.md ../md/_showlist.md
cd ..

# add list to the index page and readme page
cat md/_index.md md/_showlist.md > md/index.txt
cat md/_readme.md md/_showlist.md > README.txt

##--------- Run Pandoc Execute: ----------------------------------------------------##

# in ART125/md
cd md

# run pandoc on all files with a .md suffix, creating a file with a .md.txt suffix. 
find . -name \*.txt -type f -exec pandoc -f markdown -t html -o {}.html {} \;
find . -name \*.txt -type f -exec pandoc -f markdown -t docx -o {}.docx {} \;


# move new files to ART125/units and ART125/word
find . -name "*.txt.html" -exec mv {} ../HTMLraw \;
find . -name "*.txt.docx" -exec mv {} ../word_files \;

cd ../HTMLraw

# Remove .txt from the name
for file in *.txt.html ; do mv $file `echo $file | sed 's/\(.*\.\)txt.html/\1html/'` ; done

# Copy files and add HTML header and footer
cd ..
cp -a HTMLraw/. HTML
cd HTML
for file in *.html; do (cat ../_HEADER.txt $file ../_FOOTER.txt) > tmp; mv tmp $file; done

# Remove .txt from the name
cd ../word_files
for file in *.txt.docx ; do mv $file `echo $file | sed 's/\(.*\.\)txt.docx/\1docx/'` ; done
# Remove useless index.docx
rm index.docx

# batch commit all new files with timestamp
CMT="pandoc batch "
CMT=$CMT$(date +"%Y-%m-%d-%T")
git commit -a -m "$CMT"
